module.exports = [
  'Hi, I just got back in the area and am looking to pick up a regular serious partner. I have a flexible schedule so weekday daytime climbing works too!',
  'I\'m safe and reliable, and my stoke factor is high. I work M-F 8-5 so evenings and weekends are my free time unless I schedule something in advance.',
  'I am looking for climbing partner(s)/mentor(s) for sport climbing, as well as suggestions for great routes to climb.',
  'I\'m an experienced climber looking for a good partner to climb with. Have a flexible schedule.',
  'Hi, looking for a regular gym partner to climb weekdays after work (anytime in 5:00pm to 9:00pm range), would like to go at least 2-3 times a week.',
  'Will belay for tacos. Down for sport, bouldering, slacklining, street tacos, or whatever. Lemme know!',
  'I\'m looking for a belay partner for weekday evenings. Any climbing level is fine as long as you are a safe, attentive belayer.',
  'Looking for a consistent evening lead partner, preferably someone who can generally start around 6. Bonus points if you\'re single and hot. Just kidding, kind of ...',
  'Looking for more gym partners. I lead 10s and 11s in the gym, happy to belay you on whatever or toprope.',
  'Getting back into climbing after a year and a half hiatus while I finished school. Hit me up!',
  'Just moved to the area and am super eager to find partners to belay with indoors or get outside with.',
  'Looking for a regular partner, either before 7 am or after 7pm any day but Monday. Lead 9/10a, but projecting 10d on TR, V3 & V4 bouldering.',
  'Looking for gym climbing partners on Mondays or Thursdays. Pretty flexible on schedule but super early is typically better than super late.',
  'YOOO! I am looking to meet some people that are down for a good time! I am top rope belay certified and soon to do a lead test within the next month.',
  'I moved to the area last summer, and am looking for regular gym partners in the 5.11 / 5.12 range to project climbs and help each other push into sending at 5.12 level.',
  'Have been climbing for 10+ years and never dropped anyone.  Pretty easy going about what gets climbed -- lead or TR.',
  'I\'m looking for climbing partners to climb with on the regular. Looking to expand my climbing group to some partners with more availability.',
  'I\'m looking to get back into climbing shape with some regular partners. Right now, I have most evenings and weekends free.',
  'Looking to climb with a few more partners, preferably lead. I work part-time and climb a ton, so don\'t hesitate to reach out.',
  'Hey, looking for an indoor climbing partner.  I\'d like to go a few times a week after work (6 or later).  Let me know if you\'d like to climb!',
  'Looking for more partners to train with. Currently leading 11’s, and want to get stronger this year! Have occasional weekdays free, or can climb around 5pm after work.',
  'WILL BELAY FOR TIPS. I\'m looking to get as much practice as I can belaying. I\'m a new climber and want to hone my skills ASAP.',
  'I try to go to the gym twice a week, during that lovely busy time after work on the weekdays (earliest I can get there is 6).  Looking for a regular weekly partner.',
  'I am looking for a weekday lead partner to climb with. I’ll be doing ~3 evenings a week after work. Any time after 5 would be excellent!',
  'Looking for after work climbing buddies, weekend trip buddies and anyone that wants to share their favorite climbing spot with me.'
];
